// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace 머신러닝_주차예측ML.Model
{
    public class ModelInput
    {
        [ColumnName("SystemCodeNumber"), LoadColumn(0)]
        public string SystemCodeNumber { get; set; }


        [ColumnName("Capacity"), LoadColumn(1)]
        public float Capacity { get; set; }


        [ColumnName("Occupancy"), LoadColumn(2)]
        public float Occupancy { get; set; }


        [ColumnName("LastUpdated"), LoadColumn(3)]
        public string LastUpdated { get; set; }


    }
}
