// This file was auto-generated by ML.NET Model Builder. 

using System;
using Microsoft.ML.Data;

namespace 머신러닝_주차예측ML.Model
{
    public class ModelOutput
    {
        public float Score { get; set; }
    }
}
